;; -*- mode: eask; lexical-binding: t -*-

(package "poly-markdown"
         "0.2.2"
         "Polymode for markdown-mode")

(website-url "https://github.com/polymode/poly-markdown")
(keywords "emacs")

(package-file "poly-markdown.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25")
(depends-on "polymode")
(depends-on "markdown-mode")

(development
 (depends-on "yaml-mode"))
